### ISSUE TITLE
No licensing information available

### ISSUE THREAD

**Issue by marcokrikke** [eyal-lupu/eyallupu-blog#2]
Your solution to CSRF attacks seems like a nice one, especially with Spring 3.1!

Could you please provide any licensing information, so other developers are aware of this when possibly reusing your code? Thanks.

**Comment by jzapat11** [comment]
Great. I just found this and look amazing. I'll take some blocks of your code to add it to my project. Thanks.

**Comment by eyal-lupu** [comment]
Added Apache 2.0 license at the root of the repository
